<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>local.mmm</groupId>
        <artifactId>velocity-maxplayers-bridge-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>velocity-maxplayers-bridge-velocity</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.velocitypowered</groupId>
            <artifactId>velocity-proxy</artifactId>
            <version>3.5.0-SNAPSHOT-601</version>
            <scope>system</scope>
            <systemPath>E:/MCserver/MMM/Velocity/velocity-3.5.0-SNAPSHOT-601.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.16</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
