name: MMMVelocityBridge-Purpur
version: 2.0.1
main: local.mmm.paperbridge.PaperBridgePlugin
api-version: "1.21"
author: Xiaomenxin
provides:
  - MMMProxyStats-Purpur
softdepend:
  - MMMFlight
  - PlaceholderAPI
